version: '1.0'

services:
  app:
    image: 'review-app:1.0'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/review_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=abdo
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    ports:
      - 8080:8080

  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abdo
    ports:
      - 5432:5432
